### ISSUE TITLE
iFrame compatibility

### ISSUE THREAD

**Issue by temdo** [rapiddev/social-messenger#1]
Guys, first of all, thanks a lot for your plugin, it's incredible! 

One thing is spoiling my happiness. One of the pages on my website contains iFrame: https://moneysend.co.il/en/send/. On this page, your plugin fails - it ignores its settings (minimize on show = enabled, chat position = right). As you can see, the chat window appears on the left and it's opened. On the other pages everything works fine. 

Can you please check and fix this?

**Comment by pomianowski** [comment]
'Service is temporary unavailable.' I can not check it
But I'm going to rewrite the plugin in the next few days because I want to improve its functionality. So please look carefully at the updates and also check out our other plugins
[RapidDev on WordPress](https://profiles.wordpress.org/rapiddev#content-plugins)

**Comment by temdo** [comment]
It was turned it off because it disturbed users by instant popping up. I made a separate page for demonstration: https://moneysend.co.il/en/messenger-test/. Mind the difference between its  behavior on this page and other pages.

**Comment by pomianowski** [comment]
html, line: 290:
`<div class="wpb_wrapper"<style>iframe{width: 1px;min-width: 100%;height: 300px;}</style>`

This line of code changes the way chat is displayed

**Comment by temdo** [comment]
I've fixed it. Thanks a lot!

**Comment by pomianowski** [comment]
Great, I'm happy and if you have any other questions, I invite you to write :)
